ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS expertise TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS availability BOOLEAN DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS contact VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar TEXT;
