services:
  - type: web
    name: bridgeher-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        fromDatabase:
          name: bridgeher-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000

databases:
  - name: bridgeher-db
    databaseName: bridgeherdb
    user: bridgeher
    plan: free
